name: CI
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: |
          echo "listing available Xcode versions:"
          ls -d /Applications/Xcode*

          sudo xcode-select --switch /Applications/Xcode_15.0.1.app/Contents/Developer

      - name: Test
        run: swift test
